[NT-1578] Argo deprecation
kickstarter/ios-oss pull request #1323
Opened 2020-10-27 15:24 UTC by andrewKstrt

# 📲 What

Argo deprecation

# 🤔 Why

Some background context on why the change is needed.

# 🛠 How

More in-depth discussion of the change or implementation.

# 👀 See

Trello, screenshots, external resources?

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# ♿️ Accessibility 

- [ ] Tap targets use minimum of 44x44 pts dimensions
- [ ] Works with VoiceOver
- [ ] Supports Dynamic Type 

# 🏎 Performance

- [ ] Optimized Blended Layers (screenshots)

# ✅ Acceptance criteria

- [ ] Steps to test this feature
- [ ] Environment to test on
- [ ] Issues to look out for

# ⏰ TODO

- [ ] Got planned refactors to come
- [ ] Will add more tests
- [ ] Need feedback on a design

2020-10-28 12:16 UTC, nativeksr commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| KsApi/models/LocationTests.swift | spaceAroundOperators |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-30 00:41 UTC, singhhari requested changes

2020-10-30 00:41 UTC, singhhari commented on KsApi/models/Project.CountryTests.swift
> +    XCTAssertEqual(country, Project.Country.decodeJSONDictionary(country!.encode()))
Can we avoid the ! here?

2020-10-30 00:41 UTC, singhhari commented on KsApi/models/ShippingRule.swift
> +/*
Why did you leave this commented out?

2020-10-30 16:04 UTC, andrewKstrt commented on KsApi/lib/TryDecodable.swift
> +public func tryDecodable<T: Swift.Decodable>(_ json: JSON?) -> Decoded<T?> {
we have it in case we'll need flip some of the models back to Argo in case of json parsing issue

2020-10-30 16:10 UTC, andrewKstrt commented on KsApi/models/Backing.swift
> -      <*> (json <| "bonus_amount" <|> .success(0.0))
we do account for it at Swift.Decodable implementation 

`self.bonusAmount = try values.decodeIfPresent(Double.self, forKey: .bonusAmount) ?? 0.0`

I'm not sure about it's meaning though

2020-11-02 15:26 UTC, andrewKstrt commented on KsApi/models/ActivityEnvelope.swift
> +extension ActivityEnvelope.UrlsEnvelope: Swift.Decodable {}
it should be auto synthesized by conforming to `Swift.Decodable `

2020-11-02 15:28 UTC, andrewKstrt commented on KsApi/models/ActivityTests.swift
> +    let activity: Activity! = Activity.decodeJSONDictionary([
there are 2 functions `decodeJSONDictionary` - one throwing exception, another returning optional value. The use of force unwrap is needed for compiler to understand which function to use

2020-11-02 15:33 UTC, andrewKstrt commented on KsApi/models/Backing.swift
> +    case paymentSource = "payment_source"
`decodeIfPresent` should account for failing to parse `PaymentSource`

2020-11-02 15:36 UTC, andrewKstrt commented on KsApi/models/ErrorEnvelope.swift
> +  private let data: AltErrorMessage?
the server can return 2 different error types, we use `data` as a wrapper to parse 2nd error type

2020-11-02 17:38 UTC, singhhari approved these changes
lgtm

2020-11-02 17:39 UTC, merged