[NT-2120] Migrating query for fetching user backings to Apollo.
kickstarter/ios-oss pull request #1572
Opened 2021-07-29 22:46 UTC by singhhari

# 📲 What

One of the ways we fetch a users backings is by using a GraphQL query that provides us all  backings for a given user. The query technically works for all backings, regardless of `BackingState`  but our specific use case on this application is just for errored backings. This PR will handle the migration from our legacy DSL to Apollo GraphQL client. 

# 🤔 Why

This is simply another step forward in our larger implementation of Apollo GraphQL. We are migrating all queries, migrations and networking logic to Apollo for simplicity of use.

# 🛠 How

- Rename `BackingsEnvelope` to `ErroredBackingsEnvelope` to more accurately reflect the data types usage.
- Update the `fetchGraphUserBackings` method in our `Service` object to use Apollo GraphQL client.
- Add a new query for fetching backings.
- Create an adapter that will create a `SignalProducer` from the `Data` type created in our `GraphAPI` class.

Note: Testing this required me to pair with a web engineer to manually trigger a failed payment error on staging. The testing was successful and I saw the Activity tab update with a failed error update. This will be difficult to recreate for the reviewer of the PR unless following the same steps.

# ✅ Acceptance criteria

- [ ] Launch the app on staging and verify the query to fetch user backings is occurring. It usually occurs a second or two after the tab bar renders. You can use Charles to observe the very first graph request.
- [ ] Verify the query is looking for errored backings and there is no regression
- [ ] Optional: Pair with a payments engineer to go through the steps outlined here: 
https://app.getguru.com/card/cn9ELeri/How-to-test-errored-pledge-flow-in-Kickstarter-in-staging

2021-07-29 22:52 UTC, nativeksr commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-07-29 23:17 UTC, singhhari commented on KsApi/models/ErroredBackingsEnvelope.swift
> +        let project = Project.project(from: graphProject)
I did not change this method but I think reformatting flagged codecov.

2021-07-29 23:17 UTC, singhhari commented on KsApi/models/ErroredBackingsEnvelope.swift
> +        let project = Project.project(from: projectFragment)
Can't test these producers until we get a mock GraphQL client made. We should prioritize that for next sprint and come back to fix all of these untested adapter methods.

2021-07-30 16:30 UTC, msadoon requested changes
Some changes (discussed in 1-1 as well).

2021-07-30 16:41 UTC, singhhari commented on KsApi/models/ErroredBackingsEnvelope.swift
> +        let project = Project.project(from: graphProject)
Deleted in the last commit.

2021-07-30 17:03 UTC, singhhari commented on KsApi/models/ErroredBackingsEnvelope.swift
> +        let project = Project.project(from: projectFragment)
Added a test in the last commit that should hold us over until we add the mock client.

2021-07-30 17:08 UTC, singhhari commented on KsApi/Service.swift
> +    -> SignalProducer<ErroredBackingsEnvelope, ErrorEnvelope> {
Renamed method to `fetchErroredUserBackings`.

2021-07-30 17:10 UTC, singhhari commented on KsApi/queries/FetchUserBackings.graphql
> +            startsAt
good catch!

2021-07-30 17:50 UTC, msadoon approved these changes
yep, good to go!

2021-07-30 18:10 UTC, merged