[NTV-201] Adding environmental commitments to new project page
kickstarter/ios-oss pull request #1628
Opened 2021-10-29 15:45 UTC by singhhari

# 📲 What

Adding the Environmental Commitments section to our new project page. Upon selection of the tab in the navigation selector, we will navigate to the new view controller and render a table view of environmental commitments. The very last cell (or in the case when no environmental commitments are returning from the API) we show a "footer" cell that enables users to navigate to a webview of our Environmental Resources Center.

# 🛠 How

Created a couple of new table view cells to register for our `EnvironmentalCommitmentsViewController`. Each cell and the view controller has its own view model that can micromanage its logic. Moreover we're using a delegate to enable the presentation of the `HelpWebViewController`.

# 👀 See

https://user-images.githubusercontent.com/15615702/139474040-d55fed28-300d-4ba2-a955-2a2b51bbbcd5.mp4

# ✅ Acceptance criteria

- [x] Navigate to a project in the `Popular` tab. Find one with environmental commitments like [this one](https://www.kickstarter.com/projects/flatoutgames/verdant) and verify you can see the environmental commitments and the footer cell showing a hyperlink.
- [x] Tap on the hyperlink and verify a web view controller is presented and navigates to our Environmental Resources Center.
- [ ] Similarly, find a project with no environmental commitments and verify only the footer cell is showing.

2021-11-01 18:05 UTC, msadoon requested changes
Code looks decent, there's one issue with respect to the `footer`, pretty sure it could just be a table view footer and doesn't need to be its' own cell.
Also a few other code -related comments.

Ran app on sim, found a few issues:
alignment to header title is a little off: [prototype](https://www.figma.com/file/Vk262JvQlfddgdkfXN0rx0/Native%3A-Project-Page-C5-2021?node-id=166%3A5281)
<img src="https://user-images.githubusercontent.com/4282741/139718238-99684efb-f582-
43dd-b97d-5bf0e7382d99.png" width="300">

Also noticed on ipad only that after opening the web view and closing it, the contents of the entire project page are gone.
<img src="https://user-images.githubusercontent.com/4282741/139718440-4c3af4a5-b4c0-4e6a-bbeb-06bfe4e068f4.gif" width="300">

And on a similar note, I know that we restrict the FAQ page contents to if the user is logged in. Are we still doing that with environmental commitments? Seems a product question mostly, but it would be strange to show one section and not another based on log in state, unless that's the intention of the API.
<img src="https://user-images.githubusercontent.com/4282741/139718978-8098c140-5236-42a1-8089-4bec5a44b06b.gif" width="300">

2021-11-01 21:31 UTC, singhhari commented on Kickstarter-iOS/DataSources/ProjectEnvironmentalCommitmentsDataSource.swift
> +    case footer
I've decided to rename this section and its respective cell from `Footer` to `Disclaimer`. I agree that using the word footer is misleading but I do not think it is worth the effort of changing this implementation given the significant re-factor I'm going to have to work on right after this.

2021-11-01 21:31 UTC, singhhari commented on Kickstarter-iOS/Views/Cells/ProjectEnvironmentalCommitmentFooterCell.swift
> +    let environmentString = "<a href=\(environmentLink)>Visit our Environmental Resources Center</a>"
I'm unsure what the suggestion is here? There already is a TODO at the top of this method that suggests the string needs to be internationalized, I'll add another line of details to it?  

More importantly though, the string we submit will very likely be these two, word-for-word. The one with the anchor tag will need to be submitted exactly like that so the translation is wrapped by that tag and the UITextView delegate method can detect it. If you look at the `attributedDisclaimerText` method, the String being localized is using this same method and the argument to the method is a URL that gets embedded in the anchor tag. We will be employing the exact same method here. I think once we get the translations back we can clean up the method but for the most part I don't think there is a way to simplify applying separate attributes to both strings and then combining them. Open to suggestions.

2021-11-01 21:32 UTC, singhhari commented on Kickstarter-iOS/Views/Controllers/ProjectEnvironmentalCommitmentsViewControllerTests.swift
> +    ]
Good catch. Updated.

2021-11-01 21:34 UTC, singhhari commented
> Code looks decent, there's one issue with respect to the `footer`, pretty sure it could just be a table view footer and doesn't need to be its' own cell. Also a few other code -related comments.
> 
> Ran app on sim, found a few issues: alignment to header title is a little off: [prototype](https://www.figma.com/file/Vk262JvQlfddgdkfXN0rx0/Native%3A-Project-Page-C5-2021?node-id=166%3A5281) <img alt="" width="300" src="https://user-images.githubusercontent.com/4282741/139718238-99684efb-f582-43dd-b97d-5bf0e7382d99.png">
> 
> Also noticed on ipad only that after opening the web view and closing it, the contents of the entire project page are gone. <img alt="" width="300" src="https://user-images.githubusercontent.com/4282741/139718440-4c3af4a5-b4c0-4e6a-bbeb-06bfe4e068f4.gif">
> 
> And on a similar note, I know that we restrict the FAQ page contents to if the user is logged in. Are we still doing that with environmental commitments? Seems a product question mostly, but it would be strange to show one section and not another based on log in state, unless that's the intention of the API. <img alt="" width="300" src="https://user-images.githubusercontent.com/4282741/139718978-8098c140-5236-42a1-8089-4bec5a44b06b.gif">

Nice eye here. I was adding a small margin without realizing it was slightly off. Good catch.

As for the log in state issue, I'm not sure why we have a difference here. That's definitely a product question but my assumption is that the Environmental Resources center is available to unauthenticated users anyway so there's no reason to restrict access to it. Asking a question to the creator does seem like something that requires the context of a logged in user so the creator knows who is asking.

2021-11-02 14:29 UTC, msadoon commented on Kickstarter-iOS/Views/Cells/ProjectEnvironmentalCommitmentFooterCell.swift
> +    let environmentString = "<a href=\(environmentLink)>Visit our Environmental Resources Center</a>"
Yea its' fine for now, my suggestion was to add the `//TODO:` here to address that we're not driving this `String` through `Localizable.strings`, as done with `atttributedDisclaimerText` right? So yes we need to wait for translations for that which is fine, I just want to be aware that we don't won't two ways to generate links for a string, `Localizable` _and_ `a href=` scattered elsewhere, just a convention really, but helps keep our code base clean. Also I don't see examples of `a href` anywhere else in the code, just trying to be careful about introducing new methods of generating `Strings` is all :)

2021-11-02 14:41 UTC, msadoon commented on Library/ViewModels/ProjectEnvironmentalCommitmentsViewModelTests.swift
> +    ]
I think you may have forgotten to push the change here.

2021-11-02 14:46 UTC, msadoon approved these changes
Ok looks good,

Just push that last change with the tests property being declared globally and we're good I think. We can address the Strings issue once we do the actual Strings upload.

Great job!

2021-11-02 15:16 UTC, singhhari commented on Library/ViewModels/ProjectEnvironmentalCommitmentsViewModelTests.swift
> +    ]
Yup lol sry about that. Pushing it up in this last commit.

2021-11-02 15:42 UTC, msadoon commented on Kickstarter-iOS/Views/Cells/ProjectEnvironmentalCommitmentFooterCell.swift
> +    let environmentString = "<a href=\(environmentLink)>Visit our Environmental Resources Center</a>"
Cool, just wanted to point out while it ofcourse used in multiple places in our codebase, the only place its' used outside of `Strings` or `Localizable` is `DisclaimerCell` :)

2021-11-02 15:51 UTC, merged