[NTV-240] - Project Page Tab Segment Events
kickstarter/ios-oss pull request #1641
Opened 2021-11-22 21:30 UTC by msadoon

# 📲 What

Send segment events for new project page tabs as described in this [ticket](https://kickstarter.atlassian.net/browse/NTV-240).

# 🤔 Why

We need event tracking for brand marketing and effectiveness-evaluation purposes.

# 🛠 How

Reused previously built `KSRAnalytics.SectionContext` and added a `tabSelected` field for new set of enum values called `TabContext`.

# ✅ Acceptance criteria

- [ ] With New Project Page flag on, switch between tabs in a project, should see the "Page Viewed" event fired with the "context_section" equal to the tab the user clicked.

2021-11-22 22:06 UTC, paulomcg requested changes

2021-11-22 22:06 UTC, paulomcg commented on Library/Tracking/KSRAnalytics.swift
> +        case .environmentalCommitments: return "environmental commitments"
This one should be `environment`

2021-11-22 22:06 UTC, paulomcg commented on Library/Tracking/KSRAnalytics.swift
> +        case .faqs: return "faqs"
Should be `faq`

2021-11-23 12:18 UTC, Arkariang approved these changes
lgtm!

2021-11-23 15:18 UTC, merged