[Prototype] Replace Backer Dashboard Backed/Saved Tabs With SwiftUI Version
kickstarter/ios-oss pull request #1753
Opened 2022-11-03 14:35 UTC by scottkicks

# 📲 What

As we consider integrating SwiftUI into our iOS app, I'd like to get a feel for how this would work myself in an effort to provide more useful feedback and understand the pros/cons. 

There's an existing prototype PR for replacing an entire screen [here](https://github.com/kickstarter/ios-oss/pull/1750), so for this PR I wanted to work through a slightly different context...
1. How does a piecemeal approach look?
2. How can we replace a UIKit view that exists inside of a storyboard with a SwiftUI view. 

# 🤔 Why

Check out this [doc](https://kickstarter.atlassian.net/l/cp/a96RSutZ) for more info on why SwiftUI could benefit KS.

# 🛠 How

- Replaces the "backed" and "saved" tabs within `BackerDasboardViewController` with a new `BackerDashboardTabBarView` (SwiftUI code)
- This new SwiftUI view is embedded in a `UIHostingViewController` and added programmatically to this ViewController 
- The UIKit tabs and selectedTabIndicator are removed from the storyboard and swift code. 

# 👀 See

UIKit 🐛 

https://user-images.githubusercontent.com/110618242/199745647-f1e37fe1-3283-44e7-8d1c-ef5dc698e286.mp4

SwiftUI 🦋

https://user-images.githubusercontent.com/110618242/199749402-a69cca28-b84f-4068-af84-87e03aa8ee59.mp4

# ✅ Acceptance criteria

- [ ] Replaces the "backed" and "saved" tabs within `BackerDasboardViewController` with a new SwiftUI `BackerDashboardTabBarView`  

# ⏰ TODO

- [ ] Add divider line between tabs and projects view (Or not? IMO it looks better without 🤷‍♂️ )
- [ ] Refactor ReactiveSwift code for showing backed/saved projects, or empty states, based on selected tab using Combine
- [ ] Add accessibility labels
- [ ] Update snapshot tests

2022-11-03 14:49 UTC, nativeksr commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:1:1 | warning: (sortedImports) Sort import statements alphabetically. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:2:1 | warning: (sortedImports) Sort import statements alphabetically. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:9:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:11:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:13:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:24:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:25:1 | warning: (blankLinesAroundMark) Insert blank line before and after MARK: comments. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:25:1 | warning: (spaceInsideComments) Add leading and/or trailing space inside comments. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:55:1 | warning: (leadingDelimiters) Move leading delimiters to the end of the previous line. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:56:1 | warning: (leadingDelimiters) Move leading delimiters to the end of the previous line. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:57:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:71:1 | warning: (wrapArguments) Align wrapped function arguments or collection elements. |
| Kickstarter-iOS/Features/BackerDashboardPages/BackerDashboardTabBarView.swift:72:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:24:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:32:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:34:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:35:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:35:1 | warning: (wrapArguments) Align wrapped function arguments or collection elements. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:36:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:36:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:37:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:37:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:38:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:38:1 | warning: (wrapArguments) Align wrapped function arguments or collection elements. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:39:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:39:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:40:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:40:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:41:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:41:1 | warning: (wrapArguments) Align wrapped function arguments or collection elements. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:53:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:78:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:180:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:233:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:259:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:261:1 | warning: (indent) Indent code in accordance with the scope level. |
| Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift:264:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/ViewModels/BackerDashboardViewModel.swift:8:1 | warning: (redundantRawValues) Remove redundant raw string values for enum cases. |
| Library/ViewModels/BackerDashboardViewModel.swift:9:1 | warning: (redundantRawValues) Remove redundant raw string values for enum cases. |
| Library/ViewModels/BackerDashboardViewModel.swift:102:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/ViewModels/BackerDashboardViewModel.swift:104:1 | warning: (redundantSelf) Insert/remove explicit self where applicable. |
| Library/ViewModels/BackerDashboardViewModel.swift:106:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/ViewModels/BackerDashboardViewModel.swift:108:1 | warning: (redundantSelf) Insert/remove explicit self where applicable. |
| Library/ViewModels/BackerDashboardViewModel.swift:110:1 | warning: (indent) Indent code in accordance with the scope level. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-04-20 17:12 UTC, msadoon requested changes
Ok overall this approach is good, ran the app and it's almost identical to what we had before.

Let's go ahead and update this with `main` for starters, then focus on just building out the `BackerDashboardTabBarView`. So the next step is to have only one file added `BackerDashboardTabBarView`.

Once all the spacing/fonts look identical to what we had before - we can go ahead and build out the functionality.

For testing - remove all the changes except the ones' commented on in `BackerDashboardViewController`.

So only three files should be added/changed in this pr's next review: `BackerDashboardTabBarView`, `project.pbxproj` and `BackerDasboardViewController`.

Obviously this is cool bonus stuff we can release so take your time and have fun with it!

To test this let's try this approach and not delete any existing code.

2023-06-07 13:58 UTC, scottkicks commented on Kickstarter-iOS/Features/BackerDashboardPages/Controller/BackerDashboardViewController.swift
> +    ))
it looks like in the latest versions we can't use the @available declaration on stored properties. 
looking into a workaround

2023-08-02 19:37 UTC, ifosli reviewed
Overall, looks pretty good! One visual change: the bar below the buttons doesn't look as nice in SwiftUI in my opinion - the weight is too much and the separator bar is missing. Also, view state is being stored in the view instead of in the view model, which is weird to me. I'm okay with this if it's intended to be temporary until the view is wired up, but I think we should revisit if it's intended to be a long term plan.

One other thing: I've noticed in the past that SwiftUI gives you a lot of things for free (dark mode support, dynamic type support, ect). Based on the code, I don't expect any problems, but please make sure you test both of these before submitting just in case we're relying on a default (white) background color somewhere.

2023-08-02 19:37 UTC, ifosli commented on Kickstarter-iOS/Features/BackerDashboardPages/SwiftUI/BackerDashboardTabView.swift
> +  @State var savedProjects: Int
I don't love this; one of the benefits of SwiftUI is that we don't need to try to keep things in sync (as long as we have a model we're observing). I think it's fine if it's intended as a temporary thing, but in the long run, we should observe a model instead.

2023-08-02 19:37 UTC, ifosli commented on Kickstarter-iOS/Features/BackerDashboardPages/SwiftUI/BackerDashboardTabView.swift
> +      currentTab = tab
In the same way, in the long run, I don't think we should update the currentTab here. Instead, we tell the model that a new tab was selected, and then we update our UI only once the model tells us a different tab is active.

2023-08-02 19:39 UTC, scottkicks commented
Just noting that this is very out of date at this point. I haven't had the bandwidth to come back to this 😢 . Keep the comments coming though!

2023-09-11 17:51 UTC, scottkicks commented
I am closing this for now. We can use this as a reference when we rebuild this screen and once we have more defined conventions.

2023-09-11 17:51 UTC, closed without merging