[WEB-1007] FetchUserEmailQuery
kickstarter/ios-oss pull request #1800
Opened 2023-03-08 18:01 UTC by scottkicks

# 📲 What

In order to reduce the amount/size of network calls to get the currently logged in user's email for our CAPI events, we can add a simpler query that just gets the email and store it globally instead of asking for the entire user object every time.

# 🤔 Why

reduces the amount of network calls needed and makes accessing the user's email simpler.

# 🛠 How

Add a small one field query in AppDelegate that will grab the email and make it accessible app-wide in AppEnvironment.currency.loggedInUserEmail .

- [ ] Steps to test this feature
- [ ] Environment to test on
- [ ] Issues to look out for

# ⏰ TODO

- [ ] Got planned refactors to come
- [ ] Will add more tests
- [ ] Need feedback on a design

2023-03-08 18:17 UTC, msadoon requested changes
Mostly there, just fix these issues.

2023-03-08 18:17 UTC, msadoon commented on KsApi/ServiceType.swift
> +  /// Fetches the email of the given User using graphQL.
Mind saying that the user in this instance has to be logged in?

2023-03-08 18:17 UTC, msadoon commented on KsApi/models/UserEnvelope.swift
> +  static func envelopeProducer(from data: GraphAPI.FetchUserEmailQuery.Data)
nice work adding it here.

2023-03-08 18:17 UTC, msadoon commented on KsApi/models/graphql/GraphUserEmailTests.swift
> +      "email": "blob@me.com"
Should be `null`

2023-03-09 19:01 UTC, nativeksr commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| Library/AppEnvironment.swift:45:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/Environment.swift:47:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/ViewModels/PledgePaymentMethodsViewModel.swift:388:1 | warning: (redundantParens) Remove redundant parentheses. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-03-13 14:54 UTC, nativeksr commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| Library/ViewModels/PledgeViewModelTests.swift:1965:1 | warning: (consecutiveBlankLines) Replace consecutive blank lines with a single blank line. |
| Library/ViewModels/PledgeViewModelTests.swift:2070:1 | warning: (consecutiveBlankLines) Replace consecutive blank lines with a single blank line. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-03-14 21:04 UTC, msadoon requested changes
Some minor things here to update, but overall pretty good.
Mostly just get that signal firing from `userSessionStarted`.

2023-03-14 21:04 UTC, msadoon commented on Library/ViewModels/PledgeViewModel.swift
> +
can probably remove this newline, format might do it, if not don't worry about it.

2023-03-15 02:07 UTC, nativeksr commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-03-15 14:45 UTC, scottkicks commented on Kickstarter-iOS/AppDelegateViewModel.swift
> +        self.applicationLaunchOptionsProperty.signal.ignoreValues(),
@msadoon I wanted to account for the case where users are already logged in when the feature is turned on. This way the next time they open the app we make sure to set their email. As opposed to waiting until they've logged out and then back in.

Does that make sense?

2023-03-15 14:51 UTC, msadoon commented on Kickstarter-iOS/AppDelegateViewModel.swift
> +        self.applicationLaunchOptionsProperty.signal.ignoreValues(),
Yep, good call, didn't think about that.

2023-03-15 14:52 UTC, msadoon approved these changes
Good to go, just make that comment fix and tests pass.

2023-03-15 15:57 UTC, merged