MBL-721
kickstarter/ios-oss pull request #1817
Opened 2023-05-08 20:06 UTC by scottkicks

# 📲 What

Now that we have RemoteConfig configured, lets get our local feature flags in our debug menu working. 

# 🤔 Why

Some background context on why the change is needed.

# 🛠 How

These toggles will first reference values stored in user defaults, if there is one, before referencing the values currently published in our [firebase console](https://console.firebase.google.com/u/0/project/kickstarter-ios-alpha-94cf4/config).
Allowing us to test our app with different flags enbaled/disabled without impacting production.

We're using the same pattern here that we've had with Optimizely, so this is mostly renames and making sure that we're referencing the `RemoteConfigClientType` that is now in `AppEnvironment`

# 👀 See

Trello, screenshots, external resources?

| After 🦋 |
| --- |
|  ![Simulator Screen Recording - iPhone 13 Pro - 2023-05-08 at 14 05 28](https://user-images.githubusercontent.com/110618242/236922875-fdbb7e0e-481e-45f3-b2cd-810fd7e7533c.gif) |

# ✅ Acceptance criteria

Make sure you run the app using our `AppCenter Alpha` scheme to test.
- [ ] Toggling flags in Debug -> Remote Config Feature Flags persists on relaunch and fully closing the app.
- [ ] On a fresh install with Consent Management Dialog flag enabled, and the live value in the [firebase console](https://console.firebase.google.com/u/0/project/kickstarter-ios-alpha-94cf4/config) set to false, the app shows the Tracking dialog proving that the app is referencing the local flag value and not the published on

2023-05-08 20:35 UTC, nativeksr commented
<!--
  0 Errors
  1 Warning: Big PR
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-05-09 19:07 UTC, msadoon requested changes
Ok, nice quick work here.

For some reason I'm not getting the flags to show in-app:

https://github.com/kickstarter/ios-oss/assets/4282741/cb561a2e-5a0f-49b0-8aae-ac9b70d486f8

Also address the questions below and I'll take another look, likely on Thursday. I want to focus heads down and get the xcode upgrade ready for review tomorrow.

2023-05-09 19:26 UTC, scottkicks commented on Kickstarter-iOS/Features/BetaTools/Controller/BetaToolsViewController.swift
>    private func goToOptimizelyFeatureFlagTools() {
nice catch

2023-05-09 20:14 UTC, scottkicks commented
addressed your comments @msadoon take your time reviewing. no rush!

2023-05-09 20:51 UTC, msadoon approved these changes
Yep so good to go  - I noticed that the defaults load first not the dashboard values (on fresh install). Then re-launching picks up the dashboard values. Just as a discussion this seems acceptable to me, but let me know if you think dashboard values should be shown on first install launch instead of default values.

2023-05-10 15:50 UTC, merged