[MBL-897] Feature Flag Use of AI Project Tab
kickstarter/ios-oss pull request #1841
Opened 2023-08-01 17:15 UTC by msadoon

# 📲 What

Part of the new project page "Use of AI" tab.

# 🤔 Why

Feature flag is standard for launching new feature.

# 🛠 How

Added to `RemoteConfigFeatures`, `RemoteConfigFeature+Helpers`, `RemoteConfigFeatureFlagToolsViewModel`.

`use_of_ai_project_tab` also added to RemoteConfig on Firebase Remote Config. Production and 

# 👀 See

Trello, screenshots, external resources?

| Before 🐛 | After 🦋 |
| --- | --- |
| <img src="https://github.com/kickstarter/ios-oss/assets/4282741/83dc5e58-a301-49a2-8256-807b9ec018ea
"> | 
<img src="https://github.com/kickstarter/ios-oss/assets/4282741/228afd1b-f66c-4597-880a-49ee23b454f8">
 |

# ✅ Acceptance criteria

- [x] Feature flag is available for use via a helper method.

2023-08-01 17:26 UTC, nativeksr commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift:41:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift:50:1 | warning: (indent) Indent code in accordance with the scope level. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2023-08-02 14:36 UTC, scottkicks requested changes
Why is `GraphAPI` being updated 🤔? This mutation should have been updated when I cleaned up this mutation in my TriggerThirdPartyEvent implementation. 

We need this update, but it would be better to address this in its own PR and keep the context of this one to the feature flag

2023-08-02 14:37 UTC, scottkicks commented on Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
> +  }
nice add

2023-08-02 14:40 UTC, scottkicks reviewed
We also should update the feature flag view controller's snapshot tests

2023-08-02 14:40 UTC, scottkicks commented on Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
> +  func testUseOfAIProjectAI_RemoteConfig_FeatureFlag_False() {
```suggestion
  func testUseOfAIProjectTab_RemoteConfig_FeatureFlag_False() {
```

2023-08-02 14:53 UTC, msadoon commented
> We also should update the feature flag view controller's snapshot tests

Yes! Missed this, good catch.

2023-08-02 16:06 UTC, scottkicks approved these changes
👍 
just need to update with `main`

2023-08-02 17:19 UTC, merged