MBL-1226: Add stripeCardId to UserStoredCardsFragment
kickstarter/ios-oss pull request #1974
Opened 2024-03-11 21:20 UTC by amy-at-kickstarter

# 📲 What

Add `stripeCardId` to `UserStoredCardsFragment`

# 🤔 Why

From the ticket:
> When we end up calling Stripe.confirmPayment to process late pledges, we need to pass in a [paymentMethodId](https://stripe.dev/stripe-ios/stripe/documentation/stripe/stppaymentintentparams/paymentmethodid). This is accessible to us via the stripeCardId field that we can get in the UserStoredCardsFragment.

# 🛠 How

For the example ID in all the templates in the tests, `pm_1OtGFX4VvJ2PtfhK3Gp00SWK`, I created a test card on staging and pulled that ID from GraphQL.

2024-03-11 21:26 UTC, amy-at-kickstarter commented on KsApi/models/DeletePaymentMethodEnvelopeTests.swift
> +                  "stripeCardId": "pm_1OtGFX4VvJ2PtfhK3Gp00SWK",
I erred on adding this field everywhere that references `storedCards`, even if the test didn't break without the field. I'd rather the data was accurate to what we'll get back from GraphQL.

2024-03-12 13:11 UTC, scottkicks requested changes
Nice one! I'm actually realizing now that we need to do this in the `CreditCardFragment` too. 
When a user is adds a new payment method, `CreatePaymentSource` is called. It returns this fragment that we can use to pass `stripeCardId` to Stripe.confirmPayment. Sorry it wasn't in the ticket.

```swift
fragment CreditCardFragment on PaymentSource {
  ... on CreditCard {
    expirationDate
    id
    lastFour
    paymentType
    state
    type
    ---------
    stripeCardId
    ---------
  }
}
```

2024-03-12 13:24 UTC, amy-at-kickstarter commented
> Nice one! I'm actually realizing now that we need to do this in the `CreditCardFragment` too. When a user is adds a new payment method, `CreatePaymentSource` is called. It returns this fragment that we can use to pass `stripeCardId` to Stripe.confirmPayment. Sorry it wasn't in the ticket.
> 
> ```swift
> fragment CreditCardFragment on PaymentSource {
>   ... on CreditCard {
>     expirationDate
>     id
>     lastFour
>     paymentType
>     state
>     type
>     ---------
>     stripeCardId
>     ---------
>   }
> }
> ```

Ah, will do and then will ping for an updated review.

2024-03-12 13:54 UTC, amy-at-kickstarter commented
@scottkicks OK, added it to the other fragment.

FWIW, there are two GraphQL adapters for these two fragments - but I want to wait and see if we need to add this code to the adapters before modifying those. That should be a pretty obvious/easy change when we get there.

2024-03-12 15:34 UTC, scottkicks approved these changes
Thanks!

2024-03-12 17:39 UTC, merged