[MBL-1606] New Crowdfund Checkout UI
kickstarter/ios-oss pull request #2127
Opened 2024-08-20 02:26 UTC by scottkicks

# 📲 What

## I suggest reviewing commit by commit

Updates the UI according to the [new designs](https://www.figma.com/design/z4faZM4BQwbyiDe7y8tbpP/Pledge-Redemption?node-id=19-852&t=wSSXdx5F7wOTdtCM-4)

This doesn't include the new estimated shipping view yet. I'll do that in a separate PR

# 🤔 Why

[Some background context on why the change is needed.](https://kickstarter.atlassian.net/browse/MBL-1606)

# 🛠 How

- Mostly code deletion and re-ordering views
The Pledge Summary Table also needed some updates. It now more closely matches the design of the Late Pledge Checkout screen. That being said I opted to reuse some of the PostCampaign components here since late pledge will be updated to have basically the same UI. 
- The CTA view that holds the pledge buttons also needs the pledge amount displayed. `ConfirmDetailsViewController` does this, so I created a new CTA container class to keep it behind our feature flag.

# 👀 See

[Before comparison here](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2939388143/Consolidate+Checkout+Flows#Crowdfunding-Updates)

![Simulator Screen Recording - iPhone 15 Pro - 2024-08-14 at 11 19 17](https://github.com/user-attachments/assets/a3322bf2-8b5e-4295-9f65-79d1405a10ef)

# ✅ Acceptance criteria

- [x] Crowdfund checkout works as expected
- [x] New UI matches new designs
- [x] This is all behind the no shipping at checkout feature flag.

# ⏰ TODO

- Add the new estimated shipping view in a separate PR
- Rename the PostCampaign views that are being used in both flows now to a more generic name. Maybe `Checkout...`

2024-08-20 02:30 UTC, nativeksr commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: Error running SwiftFormat:
Error: [0mRunning SwiftFormat...
(lint mode - no files will be changed.)
error: Unexpected end of file at 705:1 in /Users/distiller/kickstarter/Library/SharedFunctions.swift.[0m. Updating the Danger gem might fix the issue. Your Danger version: 9.4.2, latest Danger version: 9.5.0

```
 #  from Dangerfile:8
 #  -------------------------------------------
 #  swiftformat.exclude = %w(Library/Strings.swift Library/Styles/Colors.swift)
 >  swiftformat.check_format
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-20 16:10 UTC, scottkicks commented on Library/ViewModels/NoShippingPledgeViewModelTests.swift
These are minor updates to existing tests since `configurePledgeViewCTAContainerView` now listens to the latest changes to the project and pledge total signals and emits an extra signal.

2024-08-21 18:16 UTC, ifosli requested changes
We talked offline about doing further cleanup separately, so I'm okay with leaving in the bonus amount classes for now. This needs tests, though (covering the new classes and the new pledge flow - I'd like to see both snapshot and unit tests). When the code is this complicated and is actively introducing tech debt, it's especially valuable to add tests now to make sure behavior works and stays consistent.

2024-08-21 18:16 UTC, ifosli commented on Library/ViewModels/NoShippingPledgeViewModelTests.swift
Will you also add a test to make sure the reward summary gets constructed correctly? These changes look like they're deleting tests for old behavior but I didn't notice any new tests for the new behavior.

2024-08-21 22:15 UTC, ifosli approved these changes
A few weird things in the tests but overall looks good! I think it might also be valuable to add a snapshot where the "estimated shipping" shows - this might also require the feature flag to be on in the environment the test is running in.

2024-08-21 22:15 UTC, ifosli commented on Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/NoShippingPledgeViewControllerTests/testView_HasAddOns_ShippingSelected.lang_de_device_phone4_7inch_LoggedOut.png
nit: I don't think the table is supposed to have margins on the left and right

2024-08-21 22:15 UTC, ifosli commented on Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/NoShippingPledgeViewControllerTests/testView_PledgeContext_FixPaymentMethod_ErroredCard.lang_en_device_phone4_7inch.png
nit: I think this should be "Pledge without a reward" instead of "Bonus support"

2024-08-21 22:15 UTC, ifosli commented on Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPledgeViewControllerTests.swift
> +      withEnvironment(apiService: mockService, currentUser: User.template, language: language) {
Will you turn the no shipping flag on in the environment for these tests? I'm not seeing the headings in the snapshots and I'm guessing that's why. (Also, there are a lot of them so I'm totally fine with doing minimal tests in this file if you'd rather and flesh it out once we get rid of the other tests).

2024-08-22 01:46 UTC, merged